---
apiVersion: v1
kind: Flag.Configuration

flag: UseNewWidgetsPropertyTargetGroup

enabled: true

defaultValue: true

# Conditions referencing a Property & a Target Group:
conditions:
  - allOf:
      - anyOf:
          - group:
              name: BetaUsers
      - property:
          name: userEmail
          operator: in-array
          operands:
            - aabbcc
    flagValue: false
