---
apiVersion: v1
kind: flag-configuration

flag: UseNewWidgetsTargetGroup

enabled: true

defaultValue: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: BetaUsers
    flagValue: false
