---
apiVersion: v1
kind: flag-configuration

flag: UseNewWidgetsProperty

enabled: true

defaultValue: true

conditions:
  - allOf:
      - property:
          name: orgId
          operator: in-array
          operands:
              - aabbcc
    flagValue: false
